In [3]:
ma_liste=[1,2,3,4,5,6,7,8,'hello',10.5]

In [5]:
print(ma_liste)

[1, 2, 3, 4, 5, 6, 7, 8, 'hello', 10.5]


In [6]:
ma_liste[1]

2

In [7]:
ma_liste[0]

1

In [9]:
ma_liste[2:4]

[3, 4]

In [10]:
ma_liste[:4]

[1, 2, 3, 4]

In [11]:
ma_liste[2:]

[3, 4, 5, 6, 7, 8, 'hello', 10.5]

In [16]:
ma_liste[0:2],ma_liste[4],ma_liste[5:7]

([1, 2], 5, [6, 7])

In [17]:
ma_list[-2]

NameError: name 'ma_list' is not defined

In [18]:
ma_liste[-2]

'hello'

In [19]:
ma_liste[2:-4]

[3, 4, 5, 6]

In [20]:
ma_liste[::2]

[1, 3, 5, 7, 'hello']

In [21]:
ma_liste[1::2]

[2, 4, 6, 8, 10.5]

In [22]:
ma_liste.append(2)

In [23]:
print(ma_liste)

[1, 2, 3, 4, 5, 6, 7, 8, 'hello', 10.5, 2]


In [24]:
ma_liste.insert(5,'nouvelle')

In [25]:
print(ma_liste)

[1, 2, 3, 4, 5, 'nouvelle', 6, 7, 8, 'hello', 10.5, 2]


In [27]:
ma_liste[0]='a'

In [28]:
print(ma_liste)

['a', 2, 3, 4, 5, 'nouvelle', 6, 7, 8, 'hello', 10.5, 2]


In [30]:
ma_liste[3:5]=[8,10]

In [31]:
print(ma_liste)

['a', 2, 3, 8, 10, 'nouvelle', 6, 7, 8, 'hello', 10.5, 2]


In [32]:
ma_liste[0:2]=[]

In [33]:
print(ma_liste)

[3, 8, 10, 'nouvelle', 6, 7, 8, 'hello', 10.5, 2]


In [35]:
del ma_liste[3]

In [36]:
print(ma_liste)

[3, 8, 10, 6, 7, 8, 'hello', 10.5, 2]


In [42]:
ma_liste1=[1,2,3,4,5]

In [43]:
ma_liste2=[6,7,8,9,10]

In [44]:
ma_liste3=ma_liste1+ma_liste2

In [45]:
print(ma_liste3)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


In [46]:
sum(ma_liste3)

55

In [47]:
len(ma_liste3)

10

In [48]:
ma_liste=[6,1,2,5,6,6]

In [49]:
print(ma_liste)

[6, 1, 2, 5, 6, 6]


In [50]:
ma_liste.count(6)

3

In [2]:
ma_liste1=[1,2,3,4,5]

In [3]:
ma_liste2=[1,2,3,4,5]

In [4]:
ma_liste3=ma_liste1+ma_liste2

In [5]:
print(ma_liste3)

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]


In [6]:
sum(ma_liste3)

30

In [8]:
len(ma_liste3)

10

In [9]:
ma_liste=[5,6,1,2,5,6,6]

In [10]:
ma_liste

[5, 6, 1, 2, 5, 6, 6]

In [11]:
ma_liste.count(6)

3

In [12]:
ma_liste.sort()

In [13]:
ma_liste

[1, 2, 5, 5, 6, 6, 6]

In [14]:
ma_liste.reverse()

In [15]:
ma_liste

[6, 6, 6, 5, 5, 2, 1]

In [16]:
min(ma_liste)

1

In [17]:
max(ma_liste)

6

In [22]:
tuple1=(1,2,3,4,5)

In [23]:
tuple1

(1, 2, 3, 4, 5)

In [27]:
tuple1(0)=0

SyntaxError: cannot assign to function call (<ipython-input-27-60fbbdacab5d>, line 1)

In [28]:
tuple1[1]

2

In [50]:
mes_notes=[19,7,15,9,10,6,18,10,16,14,13,10,2,20,17,8,12,10,11,4]

In [51]:
print(mes_notes)

[19, 7, 15, 9, 10, 6, 18, 10, 16, 14, 13, 10, 2, 20, 17, 8, 12, 10, 11, 4]


In [52]:
#mean
import numpy

In [53]:
numpy.mean(mes_notes)

11.55

In [56]:
moyenne_generale=11.55

In [57]:
moyenne_generale

11.55

In [58]:
min(mes_notes)

2

In [59]:
max(mes_notes)

20

In [60]:
mes_notes.sort()

In [61]:
print(mes_notes)

[2, 4, 6, 7, 8, 9, 10, 10, 10, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]


In [62]:
mes_notes.reverse()

In [63]:
print(mes_notes)

[20, 19, 18, 17, 16, 15, 14, 13, 12, 11, 10, 10, 10, 10, 9, 8, 7, 6, 4, 2]


In [64]:
mes_notes[::2]

[20, 18, 16, 14, 12, 10, 10, 9, 7, 4]

In [65]:
mes_notes[19]=6

In [66]:
print(mes_notes)

[20, 19, 18, 17, 16, 15, 14, 13, 12, 11, 10, 10, 10, 10, 9, 8, 7, 6, 4, 6]


In [69]:
mes_notes[10:14]

[10, 10, 10, 10]

In [72]:
mes_notes.count(10)

4

In [74]:
mes_notes.sort()

mes_notes

In [75]:
mes_notes

[4, 6, 6, 7, 8, 9, 10, 10, 10, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]

In [77]:
mes_notes.sort(reverse=True)

In [78]:
mes_notes

[20, 19, 18, 17, 16, 15, 14, 13, 12, 11, 10, 10, 10, 10, 9, 8, 7, 6, 6, 4]

In [79]:
mes_notes_array=numpy.array(mes_notes)

In [80]:
mes_notes_array

array([20, 19, 18, 17, 16, 15, 14, 13, 12, 11, 10, 10, 10, 10,  9,  8,  7,
        6,  6,  4])

In [81]:
mes_notes_array>10

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True, False, False, False, False, False, False, False, False,
       False, False])

In [82]:
mes_notes_array[mes_notes_array>10]

array([20, 19, 18, 17, 16, 15, 14, 13, 12, 11])

In [83]:
len(mes_notes_array[mes_notes_array>10])

10